---
- name: Install Jenkins
  hosts: Jenkins
  remote_user: ubuntu
  become: yes

  tasks:
   - name: Import a key from a url
     ansible.builtin.rpm_key:
       state: present
       key: https://pkg.jenkins.io/debian-stable/jenkins.io.key

   - name: Add Jenkins repository into sources list
     ansible.builtin.apt_repository:
       repo: deb http://pkg.jenkins.io/debian-stable binary
       state: present

   - name: Install apache httpd  (state=present is optional)
     ansible.builtin.apt:
       name: jenkins
       state: present
       update_cache: yes
   - name: Start service httpd, if not started
     ansible.builtin.service:
      name: jenkins
      state: started
      enabled: true