---
#- hosts: jenkins-master
#  become: true
- name: Install Jenkins
  hosts: jenkins
  remote_user: ubuntu
  become: yes

  tasks:
  - name: add jenkins key
    apt_key:  # ansible module to add key
      url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present

  - name: add jenkins repo
    apt_repository: #ansible module to add repo
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
      state: present

  - name: install java #install java as jenkins need jdk
    apt:
      name: openjdk-17-jre
      state: present

  - name: install jenkins  #install jenkins
    apt:
      name: jenkins
      state: present

  - name: start jenkins service
    service:
      name: jenkins
      state: started

  - name: enable jenkins to start at boot time
    service:
      name: jenkins
      enabled: yes